"""Playwright-driven page debugging helpers."""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import urlparse

from .exceptions import Send2BooxError

_ABSOLUTE_ENDPOINT_RE = re.compile(
    r"https?://[^\s\"'`<>]*(?:/api/|/v\d+/|/graphql|/rest)[^\s\"'`<>]*",
    re.IGNORECASE,
)
_RELATIVE_ENDPOINT_RE = re.compile(
    r"/(?:api/|v\d+/|graphql|rest)[^\s\"'`<>]*",
    re.IGNORECASE,
)
_TEXTUAL_CONTENT_MARKERS = (
    "application/json",
    "application/javascript",
    "application/x-javascript",
    "application/graphql",
    "application/xml",
    "application/x-www-form-urlencoded",
    "text/",
)
_STATIC_ASSET_SUFFIXES = (
    ".css",
    ".gif",
    ".ico",
    ".jpeg",
    ".jpg",
    ".js",
    ".map",
    ".png",
    ".svg",
    ".woff",
    ".woff2",
)


@dataclass(slots=True, frozen=True)
class CapturedRequest:
    """Network request captured from Playwright response hook."""

    url: str
    method: str
    status: int | None
    resource_type: str
    content_type: str | None = None
    request_body: str | None = None
    response_body: str | None = None


@dataclass(slots=True)
class InterfaceInsight:
    """Inferred endpoint metadata merged from network and script clues."""

    endpoint: str
    methods: set[str] = field(default_factory=set)
    hosts: set[str] = field(default_factory=set)
    seen_in: set[str] = field(default_factory=set)
    status_codes: set[int] = field(default_factory=set)
    samples: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "endpoint": self.endpoint,
            "methods": sorted(self.methods),
            "hosts": sorted(self.hosts),
            "seen_in": sorted(self.seen_in),
            "status_codes": sorted(self.status_codes),
            "samples": self.samples,
        }


@dataclass(slots=True)
class PlaywrightDebugReport:
    """Structured report generated by ``run_playwright_debug``."""

    page_url: str
    final_url: str
    page_title: str
    network_requests: int
    script_sources: int
    interfaces: list[InterfaceInsight]
    captured_requests: list[CapturedRequest]

    def to_dict(self) -> dict[str, Any]:
        return {
            "page_url": self.page_url,
            "final_url": self.final_url,
            "page_title": self.page_title,
            "network_requests": self.network_requests,
            "script_sources": self.script_sources,
            "interfaces": [item.to_dict() for item in self.interfaces],
            "captured_requests": [
                {
                    "url": item.url,
                    "method": item.method,
                    "status": item.status,
                    "resource_type": item.resource_type,
                    "content_type": item.content_type,
                    "request_body": item.request_body,
                    "response_body": item.response_body,
                }
                for item in self.captured_requests
            ],
        }

    def to_json(self, *, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


def extract_endpoint_candidates(source_text: str) -> set[str]:
    """Extract endpoint-like strings from arbitrary text."""

    candidates: set[str] = set()
    for pattern in (_ABSOLUTE_ENDPOINT_RE, _RELATIVE_ENDPOINT_RE):
        for match in pattern.findall(source_text):
            cleaned = _clean_candidate(match)
            if not cleaned:
                continue
            if _is_static_asset(cleaned):
                continue
            candidates.add(cleaned)
    return candidates


def analyze_interfaces(
    network_requests: Sequence[CapturedRequest],
    script_sources: Sequence[str],
) -> list[InterfaceInsight]:
    """Merge network and source-text signals into endpoint insights."""

    insights: dict[str, InterfaceInsight] = {}

    for request in network_requests:
        endpoint = _normalize_to_endpoint(request.url)
        if endpoint is None:
            continue

        item = insights.setdefault(endpoint, InterfaceInsight(endpoint=endpoint))
        item.seen_in.add("network")
        item.methods.add(request.method.upper())
        host = urlparse(request.url).netloc.strip()
        if host:
            item.hosts.add(host)
        if request.status is not None:
            item.status_codes.add(request.status)
        if request.request_body:
            item.samples.append(f"request: {request.request_body}")
        if request.response_body:
            item.samples.append(f"response: {request.response_body}")

    for source_text in script_sources:
        for candidate in extract_endpoint_candidates(source_text):
            endpoint = _normalize_to_endpoint(candidate)
            if endpoint is None:
                continue

            item = insights.setdefault(endpoint, InterfaceInsight(endpoint=endpoint))
            item.seen_in.add("script")
            host = urlparse(candidate).netloc.strip()
            if host:
                item.hosts.add(host)

    for item in insights.values():
        if len(item.samples) > 3:
            item.samples = item.samples[:3]

    return sorted(insights.values(), key=lambda item: item.endpoint)


def run_playwright_debug(
    *,
    url: str,
    headless: bool = True,
    timeout_ms: int = 30_000,
    settle_ms: int = 2_000,
    max_requests: int = 250,
    max_body_chars: int = 1_200,
) -> PlaywrightDebugReport:
    """Open a page with Playwright and infer API endpoints from captures."""

    try:
        from playwright.sync_api import Error as PlaywrightError
        from playwright.sync_api import sync_playwright
    except ModuleNotFoundError as exc:  # pragma: no cover - depends on local env
        raise Send2BooxError(
            "Playwright is not installed. Install with "
            "`pip install '.[debug]'` and run `playwright install chromium`."
        ) from exc

    captured_requests: list[CapturedRequest] = []
    script_sources: list[str] = []
    page_title = ""
    final_url = url

    def on_response(response: Any) -> None:
        if len(captured_requests) >= max_requests:
            return

        request = response.request
        content_type = response.headers.get("content-type")
        text_body = _read_text_response(
            response=response,
            content_type=content_type,
            max_chars=max_body_chars,
        )
        post_data = _trim_text(request.post_data, max_body_chars)

        captured_requests.append(
            CapturedRequest(
                url=request.url,
                method=request.method or "GET",
                status=response.status,
                resource_type=request.resource_type,
                content_type=content_type,
                request_body=post_data,
                response_body=text_body,
            )
        )

        if request.resource_type == "script" and text_body:
            script_sources.append(text_body)

    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=headless)
            context = browser.new_context(ignore_https_errors=True)
            page = context.new_page()
            page.on("response", on_response)

            page.goto(url, wait_until="domcontentloaded", timeout=timeout_ms)
            if settle_ms > 0:
                page.wait_for_timeout(settle_ms)

            final_url = page.url
            page_title = page.title()

            script_sources.append(page.content())
            script_sources.extend(
                _collect_inline_script_texts(page=page, max_body_chars=max_body_chars)
            )
            context.close()
            browser.close()

    except PlaywrightError as exc:  # pragma: no cover - depends on browser runtime
        raise Send2BooxError(f"Playwright debugging failed: {exc}") from exc

    interfaces = analyze_interfaces(captured_requests, script_sources)
    return PlaywrightDebugReport(
        page_url=url,
        final_url=final_url,
        page_title=page_title,
        network_requests=len(captured_requests),
        script_sources=len(script_sources),
        interfaces=interfaces,
        captured_requests=captured_requests,
    )


def _collect_inline_script_texts(*, page: Any, max_body_chars: int) -> list[str]:
    try:
        raw_scripts = page.eval_on_selector_all(
            "script:not([src])",
            "elements => elements.map((el) => el.textContent || '')",
        )
    except Exception:  # pragma: no cover - Playwright runtime issues
        return []

    if not isinstance(raw_scripts, list):
        return []
    trimmed_scripts: list[str] = []
    for script in raw_scripts:
        if not isinstance(script, str):
            continue
        trimmed = _trim_text(script, max_body_chars)
        if trimmed is not None:
            trimmed_scripts.append(trimmed)
    return trimmed_scripts


def _read_text_response(*, response: Any, content_type: str | None, max_chars: int) -> str | None:
    if not _is_textual_content_type(content_type):
        return None
    try:
        text = response.text()
    except Exception:  # pragma: no cover - Playwright runtime issues
        return None
    return _trim_text(text, max_chars)


def _trim_text(value: str | None, max_chars: int) -> str | None:
    if value is None:
        return None
    text = value.strip()
    if not text:
        return None
    if len(text) <= max_chars:
        return text
    return f"{text[:max_chars]}...<truncated>"


def _normalize_to_endpoint(candidate: str) -> str | None:
    parsed = urlparse(candidate)
    if parsed.scheme and parsed.netloc:
        path = parsed.path or "/"
    else:
        if not candidate.startswith("/"):
            return None
        path = candidate.split("?", 1)[0].split("#", 1)[0]

    path = re.sub(r"/{2,}", "/", path)
    if path != "/" and path.endswith("/"):
        path = path[:-1]

    if _is_static_asset(path):
        return None
    if not _looks_like_endpoint(path):
        return None
    return path


def _looks_like_endpoint(path: str) -> bool:
    lowered = path.lower()
    return (
        lowered.startswith("/api/")
        or re.match(r"^/v\d+/", lowered) is not None
        or lowered.startswith("/graphql")
        or lowered.startswith("/rest")
    )


def _is_static_asset(candidate: str) -> bool:
    parsed = urlparse(candidate)
    path = parsed.path.lower()
    return path.endswith(_STATIC_ASSET_SUFFIXES)


def _is_textual_content_type(content_type: str | None) -> bool:
    if not content_type:
        return False
    lowered = content_type.lower()
    return any(marker in lowered for marker in _TEXTUAL_CONTENT_MARKERS)


def _clean_candidate(candidate: str) -> str:
    cleaned = candidate.strip().rstrip(".,;)]}>")
    if not cleaned:
        return ""
    return cleaned
